[2023-04-30 09:06:22,566] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_etl.delete_s3_obj manual__2023-04-30T09:05:15.056494+00:00 [queued]>
[2023-04-30 09:06:22,866] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_etl.delete_s3_obj manual__2023-04-30T09:05:15.056494+00:00 [queued]>
[2023-04-30 09:06:22,885] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-04-30 09:06:22,889] {taskinstance.py:1357} INFO - Starting attempt 1 of 6
[2023-04-30 09:06:22,893] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-04-30 09:06:23,333] {taskinstance.py:1377} INFO - Executing <Task(S3DeleteObjectsOperator): delete_s3_obj> on 2023-04-30 09:05:15.056494+00:00
[2023-04-30 09:06:23,387] {standard_task_runner.py:52} INFO - Started process 1117 to run task
[2023-04-30 09:06:23,419] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_etl', 'delete_s3_obj', 'manual__2023-04-30T09:05:15.056494+00:00', '--job-id', '228', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl_taskflow.py', '--cfg-path', '/tmp/tmp3sx2ebd6', '--error-file', '/tmp/tmpn2l4u_is']
[2023-04-30 09:06:23,447] {standard_task_runner.py:80} INFO - Job 228: Subtask delete_s3_obj
[2023-04-30 09:06:25,522] {task_command.py:370} INFO - Running <TaskInstance: dag_etl.delete_s3_obj manual__2023-04-30T09:05:15.056494+00:00 [running]> on host 295d97741f96
[2023-04-30 09:06:28,638] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Victor
AIRFLOW_CTX_DAG_ID=dag_etl
AIRFLOW_CTX_TASK_ID=delete_s3_obj
AIRFLOW_CTX_EXECUTION_DATE=2023-04-30T09:05:15.056494+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-30T09:05:15.056494+00:00
[2023-04-30 09:06:28,955] {base.py:68} INFO - Using connection ID 'minio_conn' for task execution.
[2023-04-30 09:06:28,963] {base_aws.py:206} INFO - Credentials retrieved from login
[2023-04-30 09:06:30,486] {s3.py:841} INFO - Deleted: ['supermarket_sales.csv']
[2023-04-30 09:06:31,400] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag_etl, task_id=delete_s3_obj, execution_date=20230430T090515, start_date=20230430T090622, end_date=20230430T090631
[2023-04-30 09:06:31,850] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-04-30 09:06:32,461] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
