[2023-04-30 12:00:47,148] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_etl.delete_s3_obj manual__2023-04-30T11:58:50.689561+00:00 [queued]>
[2023-04-30 12:00:49,023] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_etl.delete_s3_obj manual__2023-04-30T11:58:50.689561+00:00 [queued]>
[2023-04-30 12:00:49,058] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-04-30 12:00:49,066] {taskinstance.py:1357} INFO - Starting attempt 1 of 6
[2023-04-30 12:00:49,083] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-04-30 12:00:51,251] {taskinstance.py:1377} INFO - Executing <Task(S3DeleteObjectsOperator): delete_s3_obj> on 2023-04-30 11:58:50.689561+00:00
[2023-04-30 12:00:51,637] {standard_task_runner.py:52} INFO - Started process 726 to run task
[2023-04-30 12:00:51,807] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_etl', 'delete_s3_obj', 'manual__2023-04-30T11:58:50.689561+00:00', '--job-id', '261', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl_taskflow.py', '--cfg-path', '/tmp/tmp51ocjmzz', '--error-file', '/tmp/tmp4rlvion4']
[2023-04-30 12:00:51,856] {standard_task_runner.py:80} INFO - Job 261: Subtask delete_s3_obj
[2023-04-30 12:00:55,823] {task_command.py:370} INFO - Running <TaskInstance: dag_etl.delete_s3_obj manual__2023-04-30T11:58:50.689561+00:00 [running]> on host 295d97741f96
[2023-04-30 12:01:06,296] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Victor
AIRFLOW_CTX_DAG_ID=dag_etl
AIRFLOW_CTX_TASK_ID=delete_s3_obj
AIRFLOW_CTX_EXECUTION_DATE=2023-04-30T11:58:50.689561+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-30T11:58:50.689561+00:00
[2023-04-30 12:01:07,304] {base.py:68} INFO - Using connection ID 'minio_conn' for task execution.
[2023-04-30 12:01:07,387] {base_aws.py:206} INFO - Credentials retrieved from login
[2023-04-30 12:01:17,325] {s3.py:841} INFO - Deleted: ['supermarket_sales.csv']
[2023-04-30 12:01:20,371] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag_etl, task_id=delete_s3_obj, execution_date=20230430T115850, start_date=20230430T120047, end_date=20230430T120120
[2023-04-30 12:01:21,366] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-04-30 12:01:24,000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
