[2023-05-05 05:34:07,214] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_etl.update_fact_table manual__2023-05-05T05:32:51.253337+00:00 [queued]>
[2023-05-05 05:34:07,290] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_etl.update_fact_table manual__2023-05-05T05:32:51.253337+00:00 [queued]>
[2023-05-05 05:34:07,292] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-05-05 05:34:07,294] {taskinstance.py:1357} INFO - Starting attempt 1 of 6
[2023-05-05 05:34:07,295] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-05-05 05:34:07,388] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): update_fact_table> on 2023-05-05 05:32:51.253337+00:00
[2023-05-05 05:34:07,403] {standard_task_runner.py:52} INFO - Started process 743 to run task
[2023-05-05 05:34:07,418] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_etl', 'update_fact_table', 'manual__2023-05-05T05:32:51.253337+00:00', '--job-id', '1038', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl_taskflow.py', '--cfg-path', '/tmp/tmpn47s710y', '--error-file', '/tmp/tmpf9lgo1ey']
[2023-05-05 05:34:07,421] {standard_task_runner.py:80} INFO - Job 1038: Subtask update_fact_table
[2023-05-05 05:34:07,881] {task_command.py:370} INFO - Running <TaskInstance: dag_etl.update_fact_table manual__2023-05-05T05:32:51.253337+00:00 [running]> on host 295d97741f96
[2023-05-05 05:34:08,496] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Victor
AIRFLOW_CTX_DAG_ID=dag_etl
AIRFLOW_CTX_TASK_ID=update_fact_table
AIRFLOW_CTX_EXECUTION_DATE=2023-05-05T05:32:51.253337+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-05T05:32:51.253337+00:00
[2023-05-05 05:34:08,583] {base.py:68} INFO - Using connection ID 'postgres_conn' for task execution.
[2023-05-05 05:34:08,626] {dbapi.py:213} INFO - Running statement: 
            SET search_path TO dds;
            
            --// Обновляем таблицу с фактом свежей таблицей с фактами из stage //--
            INSERT INTO fact_sales (invoice_id, branch, city, customer_type, gender,
                                    product_line, unit_price, quantity, "tax_5%", total, date,
                                    time, payment, cogs, gross_margin_percentage, gross_income, rating)
            (SELECT 
                    invoice_id, branch, city, customer_type, gender, 
                    product_line, unit_price, quantity, "tax_5%", total, date::date,
                    time, payment, cogs, gross_margin_percentage, gross_income, rating 
            FROM nds.fact_sales WHERE invoice_id NOT IN (SELECT invoice_id FROM fact_sales));
            , parameters: None
[2023-05-05 05:34:08,670] {dbapi.py:221} INFO - Rows affected: 0
[2023-05-05 05:34:08,795] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag_etl, task_id=update_fact_table, execution_date=20230505T053251, start_date=20230505T053407, end_date=20230505T053408
[2023-05-05 05:34:08,912] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-05-05 05:34:09,186] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
