[2023-05-02 13:55:56,075] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_etl.delete_s3_obj manual__2023-05-02T13:55:16.904018+00:00 [queued]>
[2023-05-02 13:55:56,238] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_etl.delete_s3_obj manual__2023-05-02T13:55:16.904018+00:00 [queued]>
[2023-05-02 13:55:56,240] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-05-02 13:55:56,241] {taskinstance.py:1357} INFO - Starting attempt 1 of 6
[2023-05-02 13:55:56,244] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-05-02 13:55:56,525] {taskinstance.py:1377} INFO - Executing <Task(S3DeleteObjectsOperator): delete_s3_obj> on 2023-05-02 13:55:16.904018+00:00
[2023-05-02 13:55:56,566] {standard_task_runner.py:52} INFO - Started process 1598 to run task
[2023-05-02 13:55:56,625] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_etl', 'delete_s3_obj', 'manual__2023-05-02T13:55:16.904018+00:00', '--job-id', '605', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl_taskflow.py', '--cfg-path', '/tmp/tmpnvb3wojz', '--error-file', '/tmp/tmpgd17r7su']
[2023-05-02 13:55:56,628] {standard_task_runner.py:80} INFO - Job 605: Subtask delete_s3_obj
[2023-05-02 13:55:58,480] {task_command.py:370} INFO - Running <TaskInstance: dag_etl.delete_s3_obj manual__2023-05-02T13:55:16.904018+00:00 [running]> on host 295d97741f96
[2023-05-02 13:56:02,023] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Victor
AIRFLOW_CTX_DAG_ID=dag_etl
AIRFLOW_CTX_TASK_ID=delete_s3_obj
AIRFLOW_CTX_EXECUTION_DATE=2023-05-02T13:55:16.904018+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-02T13:55:16.904018+00:00
[2023-05-02 13:56:02,638] {base.py:68} INFO - Using connection ID 'minio_conn' for task execution.
[2023-05-02 13:56:02,646] {base_aws.py:206} INFO - Credentials retrieved from login
[2023-05-02 13:56:04,005] {s3.py:841} INFO - Deleted: ['supermarket_sales.csv']
[2023-05-02 13:56:04,668] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag_etl, task_id=delete_s3_obj, execution_date=20230502T135516, start_date=20230502T135556, end_date=20230502T135604
[2023-05-02 13:56:05,258] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-05-02 13:56:06,054] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
