[2023-04-30 08:17:42,181] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_etl.extract_from_s3 manual__2023-04-30T08:17:21.945533+00:00 [queued]>
[2023-04-30 08:17:42,308] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_etl.extract_from_s3 manual__2023-04-30T08:17:21.945533+00:00 [queued]>
[2023-04-30 08:17:42,309] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-04-30 08:17:42,310] {taskinstance.py:1357} INFO - Starting attempt 1 of 6
[2023-04-30 08:17:42,311] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-04-30 08:17:42,459] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): extract_from_s3> on 2023-04-30 08:17:21.945533+00:00
[2023-04-30 08:17:42,472] {standard_task_runner.py:52} INFO - Started process 655 to run task
[2023-04-30 08:17:42,508] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_etl', 'extract_from_s3', 'manual__2023-04-30T08:17:21.945533+00:00', '--job-id', '137', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl_taskflow.py', '--cfg-path', '/tmp/tmpvlkw6t44', '--error-file', '/tmp/tmpqwmpa0za']
[2023-04-30 08:17:42,511] {standard_task_runner.py:80} INFO - Job 137: Subtask extract_from_s3
[2023-04-30 08:17:42,979] {task_command.py:370} INFO - Running <TaskInstance: dag_etl.extract_from_s3 manual__2023-04-30T08:17:21.945533+00:00 [running]> on host 295d97741f96
[2023-04-30 08:17:44,048] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Victor
AIRFLOW_CTX_DAG_ID=dag_etl
AIRFLOW_CTX_TASK_ID=extract_from_s3
AIRFLOW_CTX_EXECUTION_DATE=2023-04-30T08:17:21.945533+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-30T08:17:21.945533+00:00
[2023-04-30 08:17:44,064] {s3.py:861} INFO - Downloading source S3 file from Bucket raw with path supermarket_sales.csv
[2023-04-30 08:17:44,224] {base.py:68} INFO - Using connection ID 'minio_conn' for task execution.
[2023-04-30 08:17:44,236] {base_aws.py:206} INFO - Credentials retrieved from login
[2023-04-30 08:17:45,029] {python.py:173} INFO - Done. Returned value was: /opt/***/data/***_tmp__qca8j5f
[2023-04-30 08:17:45,340] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag_etl, task_id=extract_from_s3, execution_date=20230430T081721, start_date=20230430T081742, end_date=20230430T081745
[2023-04-30 08:17:45,518] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-04-30 08:17:46,576] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
