[2023-05-03 18:44:30,210] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_etl.delete_s3_obj manual__2023-05-03T18:43:51.079238+00:00 [queued]>
[2023-05-03 18:44:30,643] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_etl.delete_s3_obj manual__2023-05-03T18:43:51.079238+00:00 [queued]>
[2023-05-03 18:44:30,677] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-05-03 18:44:30,680] {taskinstance.py:1357} INFO - Starting attempt 1 of 6
[2023-05-03 18:44:30,702] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-05-03 18:44:31,741] {taskinstance.py:1377} INFO - Executing <Task(S3DeleteObjectsOperator): delete_s3_obj> on 2023-05-03 18:43:51.079238+00:00
[2023-05-03 18:44:31,848] {standard_task_runner.py:52} INFO - Started process 1234 to run task
[2023-05-03 18:44:31,896] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_etl', 'delete_s3_obj', 'manual__2023-05-03T18:43:51.079238+00:00', '--job-id', '878', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl_taskflow.py', '--cfg-path', '/tmp/tmpdo_1y8bc', '--error-file', '/tmp/tmpwu6ap7np']
[2023-05-03 18:44:31,903] {standard_task_runner.py:80} INFO - Job 878: Subtask delete_s3_obj
[2023-05-03 18:44:35,745] {task_command.py:370} INFO - Running <TaskInstance: dag_etl.delete_s3_obj manual__2023-05-03T18:43:51.079238+00:00 [running]> on host 295d97741f96
[2023-05-03 18:44:39,692] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Victor
AIRFLOW_CTX_DAG_ID=dag_etl
AIRFLOW_CTX_TASK_ID=delete_s3_obj
AIRFLOW_CTX_EXECUTION_DATE=2023-05-03T18:43:51.079238+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-03T18:43:51.079238+00:00
[2023-05-03 18:44:39,914] {base.py:68} INFO - Using connection ID 'minio_conn' for task execution.
[2023-05-03 18:44:39,926] {base_aws.py:206} INFO - Credentials retrieved from login
[2023-05-03 18:44:41,463] {s3.py:841} INFO - Deleted: ['supermarket_sales.csv']
[2023-05-03 18:44:42,273] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag_etl, task_id=delete_s3_obj, execution_date=20230503T184351, start_date=20230503T184430, end_date=20230503T184442
[2023-05-03 18:44:43,057] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-05-03 18:44:43,607] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
