[2023-05-02 15:08:35,203] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_etl_date.delete_s3_obj manual__2023-05-02T15:08:01.844950+00:00 [queued]>
[2023-05-02 15:08:35,269] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_etl_date.delete_s3_obj manual__2023-05-02T15:08:01.844950+00:00 [queued]>
[2023-05-02 15:08:35,271] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-05-02 15:08:35,287] {taskinstance.py:1357} INFO - Starting attempt 1 of 6
[2023-05-02 15:08:35,288] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-05-02 15:08:35,520] {taskinstance.py:1377} INFO - Executing <Task(S3DeleteObjectsOperator): delete_s3_obj> on 2023-05-02 15:08:01.844950+00:00
[2023-05-02 15:08:35,559] {standard_task_runner.py:52} INFO - Started process 1092 to run task
[2023-05-02 15:08:35,568] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_etl_date', 'delete_s3_obj', 'manual__2023-05-02T15:08:01.844950+00:00', '--job-id', '665', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl_taskflow_date.py', '--cfg-path', '/tmp/tmpxtyeko1g', '--error-file', '/tmp/tmp9i0aapr0']
[2023-05-02 15:08:35,596] {standard_task_runner.py:80} INFO - Job 665: Subtask delete_s3_obj
[2023-05-02 15:08:36,387] {task_command.py:370} INFO - Running <TaskInstance: dag_etl_date.delete_s3_obj manual__2023-05-02T15:08:01.844950+00:00 [running]> on host 295d97741f96
[2023-05-02 15:08:38,176] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Victor
AIRFLOW_CTX_DAG_ID=dag_etl_date
AIRFLOW_CTX_TASK_ID=delete_s3_obj
AIRFLOW_CTX_EXECUTION_DATE=2023-05-02T15:08:01.844950+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-02T15:08:01.844950+00:00
[2023-05-02 15:08:38,475] {base.py:68} INFO - Using connection ID 'minio_conn' for task execution.
[2023-05-02 15:08:38,488] {base_aws.py:206} INFO - Credentials retrieved from login
[2023-05-02 15:08:39,682] {s3.py:841} INFO - Deleted: ['supermarket_sales.csv']
[2023-05-02 15:08:39,853] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag_etl_date, task_id=delete_s3_obj, execution_date=20230502T150801, start_date=20230502T150835, end_date=20230502T150839
[2023-05-02 15:08:40,181] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-05-02 15:08:41,222] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
