[2023-04-30 09:03:33,695] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_etl.dim_time manual__2023-04-30T09:03:00.358280+00:00 [queued]>
[2023-04-30 09:03:33,818] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_etl.dim_time manual__2023-04-30T09:03:00.358280+00:00 [queued]>
[2023-04-30 09:03:33,819] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-04-30 09:03:33,820] {taskinstance.py:1357} INFO - Starting attempt 1 of 6
[2023-04-30 09:03:33,821] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-04-30 09:03:34,035] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): dim_time> on 2023-04-30 09:03:00.358280+00:00
[2023-04-30 09:03:34,044] {standard_task_runner.py:52} INFO - Started process 841 to run task
[2023-04-30 09:03:34,062] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_etl', 'dim_time', 'manual__2023-04-30T09:03:00.358280+00:00', '--job-id', '205', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl_taskflow.py', '--cfg-path', '/tmp/tmp5irhjpsg', '--error-file', '/tmp/tmphqik9sx9']
[2023-04-30 09:03:34,080] {standard_task_runner.py:80} INFO - Job 205: Subtask dim_time
[2023-04-30 09:03:34,847] {task_command.py:370} INFO - Running <TaskInstance: dag_etl.dim_time manual__2023-04-30T09:03:00.358280+00:00 [running]> on host 295d97741f96
[2023-04-30 09:03:36,584] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Victor
AIRFLOW_CTX_DAG_ID=dag_etl
AIRFLOW_CTX_TASK_ID=dim_time
AIRFLOW_CTX_EXECUTION_DATE=2023-04-30T09:03:00.358280+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-30T09:03:00.358280+00:00
[2023-04-30 09:03:37,257] {base.py:68} INFO - Using connection ID 'postgres_conn' for task execution.
[2023-04-30 09:03:38,158] {python.py:173} INFO - Done. Returned value was: None
[2023-04-30 09:03:39,352] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag_etl, task_id=dim_time, execution_date=20230430T090300, start_date=20230430T090333, end_date=20230430T090339
[2023-04-30 09:03:39,689] {local_task_job.py:221} WARNING - State of this instance has been externally set to success. Terminating instance.
[2023-04-30 09:03:39,768] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 841. PIDs of all processes in the group: [841]
[2023-04-30 09:03:39,770] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 841
[2023-04-30 09:03:39,771] {process_utils.py:75} INFO - Process psutil.Process(pid=841, status='terminated', exitcode=0, started='09:03:33') (841) terminated with exit code 0
