[2023-04-30 17:53:56,412] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_etl.delete_s3_obj manual__2023-04-30T17:52:03.144971+00:00 [queued]>
[2023-04-30 17:53:56,730] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_etl.delete_s3_obj manual__2023-04-30T17:52:03.144971+00:00 [queued]>
[2023-04-30 17:53:56,737] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-04-30 17:53:56,741] {taskinstance.py:1357} INFO - Starting attempt 1 of 6
[2023-04-30 17:53:56,746] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-04-30 17:53:57,381] {taskinstance.py:1377} INFO - Executing <Task(S3DeleteObjectsOperator): delete_s3_obj> on 2023-04-30 17:52:03.144971+00:00
[2023-04-30 17:53:57,441] {standard_task_runner.py:52} INFO - Started process 772 to run task
[2023-04-30 17:53:57,581] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_etl', 'delete_s3_obj', 'manual__2023-04-30T17:52:03.144971+00:00', '--job-id', '339', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl_taskflow.py', '--cfg-path', '/tmp/tmp66bxycsx', '--error-file', '/tmp/tmpa8u6p5ma']
[2023-04-30 17:53:57,605] {standard_task_runner.py:80} INFO - Job 339: Subtask delete_s3_obj
[2023-04-30 17:54:02,031] {task_command.py:370} INFO - Running <TaskInstance: dag_etl.delete_s3_obj manual__2023-04-30T17:52:03.144971+00:00 [running]> on host 295d97741f96
[2023-04-30 17:54:13,338] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Victor
AIRFLOW_CTX_DAG_ID=dag_etl
AIRFLOW_CTX_TASK_ID=delete_s3_obj
AIRFLOW_CTX_EXECUTION_DATE=2023-04-30T17:52:03.144971+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-30T17:52:03.144971+00:00
[2023-04-30 17:54:13,709] {base.py:68} INFO - Using connection ID 'minio_conn' for task execution.
[2023-04-30 17:54:13,861] {base_aws.py:206} INFO - Credentials retrieved from login
[2023-04-30 17:54:19,732] {s3.py:841} INFO - Deleted: ['supermarket_sales.csv']
[2023-04-30 17:54:22,474] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag_etl, task_id=delete_s3_obj, execution_date=20230430T175203, start_date=20230430T175356, end_date=20230430T175422
[2023-04-30 17:54:24,404] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-04-30 17:54:27,920] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
