[2023-05-02 10:44:19,376] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_etl.fact_nds manual__2023-05-02T10:43:11.140829+00:00 [queued]>
[2023-05-02 10:44:19,442] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_etl.fact_nds manual__2023-05-02T10:43:11.140829+00:00 [queued]>
[2023-05-02 10:44:19,445] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-05-02 10:44:19,446] {taskinstance.py:1357} INFO - Starting attempt 1 of 6
[2023-05-02 10:44:19,448] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-05-02 10:44:19,557] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): fact_nds> on 2023-05-02 10:43:11.140829+00:00
[2023-05-02 10:44:19,568] {standard_task_runner.py:52} INFO - Started process 1699 to run task
[2023-05-02 10:44:19,577] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_etl', 'fact_nds', 'manual__2023-05-02T10:43:11.140829+00:00', '--job-id', '482', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl_taskflow.py', '--cfg-path', '/tmp/tmpktmporpr', '--error-file', '/tmp/tmpwium1f6_']
[2023-05-02 10:44:19,580] {standard_task_runner.py:80} INFO - Job 482: Subtask fact_nds
[2023-05-02 10:44:19,972] {task_command.py:370} INFO - Running <TaskInstance: dag_etl.fact_nds manual__2023-05-02T10:43:11.140829+00:00 [running]> on host 295d97741f96
[2023-05-02 10:44:20,769] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Victor
AIRFLOW_CTX_DAG_ID=dag_etl
AIRFLOW_CTX_TASK_ID=fact_nds
AIRFLOW_CTX_EXECUTION_DATE=2023-05-02T10:43:11.140829+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-02T10:43:11.140829+00:00
[2023-05-02 10:44:20,859] {base.py:68} INFO - Using connection ID 'postgres_conn' for task execution.
[2023-05-02 10:44:21,166] {base.py:68} INFO - Using connection ID 'postgres_conn' for task execution.
[2023-05-02 10:44:22,318] {python.py:173} INFO - Done. Returned value was: None
[2023-05-02 10:44:22,484] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag_etl, task_id=fact_nds, execution_date=20230502T104311, start_date=20230502T104419, end_date=20230502T104422
[2023-05-02 10:44:22,603] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-05-02 10:44:22,946] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
