[2023-05-02 13:53:10,888] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_etl.clear_data_directory manual__2023-05-02T13:51:38.744363+00:00 [queued]>
[2023-05-02 13:53:10,949] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_etl.clear_data_directory manual__2023-05-02T13:51:38.744363+00:00 [queued]>
[2023-05-02 13:53:10,950] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-05-02 13:53:10,951] {taskinstance.py:1357} INFO - Starting attempt 1 of 6
[2023-05-02 13:53:10,952] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-05-02 13:53:11,039] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): clear_data_directory> on 2023-05-02 13:51:38.744363+00:00
[2023-05-02 13:53:11,049] {standard_task_runner.py:52} INFO - Started process 1350 to run task
[2023-05-02 13:53:11,057] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_etl', 'clear_data_directory', 'manual__2023-05-02T13:51:38.744363+00:00', '--job-id', '595', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl_taskflow.py', '--cfg-path', '/tmp/tmp8tt0uvcl', '--error-file', '/tmp/tmp6r4t4f7l']
[2023-05-02 13:53:11,060] {standard_task_runner.py:80} INFO - Job 595: Subtask clear_data_directory
[2023-05-02 13:53:11,463] {task_command.py:370} INFO - Running <TaskInstance: dag_etl.clear_data_directory manual__2023-05-02T13:51:38.744363+00:00 [running]> on host 295d97741f96
[2023-05-02 13:53:12,206] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Victor
AIRFLOW_CTX_DAG_ID=dag_etl
AIRFLOW_CTX_TASK_ID=clear_data_directory
AIRFLOW_CTX_EXECUTION_DATE=2023-05-02T13:51:38.744363+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-02T13:51:38.744363+00:00
[2023-05-02 13:53:12,217] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-05-02 13:53:12,220] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'rm -rf ${pwd}data/* | echo "приехали"']
[2023-05-02 13:53:12,242] {subprocess.py:85} INFO - Output:
[2023-05-02 13:53:12,298] {subprocess.py:92} INFO - приехали
[2023-05-02 13:53:12,352] {subprocess.py:96} INFO - Command exited with return code 0
[2023-05-02 13:53:12,740] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag_etl, task_id=clear_data_directory, execution_date=20230502T135138, start_date=20230502T135310, end_date=20230502T135312
[2023-05-02 13:53:12,826] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-05-02 13:53:13,091] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
