[2023-05-03 18:35:12,986] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_etl.extract_from_s3 manual__2023-05-03T18:34:59.697678+00:00 [queued]>
[2023-05-03 18:35:13,065] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_etl.extract_from_s3 manual__2023-05-03T18:34:59.697678+00:00 [queued]>
[2023-05-03 18:35:13,066] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-05-03 18:35:13,068] {taskinstance.py:1357} INFO - Starting attempt 1 of 6
[2023-05-03 18:35:13,069] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-05-03 18:35:13,186] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): extract_from_s3> on 2023-05-03 18:34:59.697678+00:00
[2023-05-03 18:35:13,201] {standard_task_runner.py:52} INFO - Started process 474 to run task
[2023-05-03 18:35:13,216] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_etl', 'extract_from_s3', 'manual__2023-05-03T18:34:59.697678+00:00', '--job-id', '854', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl_taskflow.py', '--cfg-path', '/tmp/tmpabiiq2u0', '--error-file', '/tmp/tmp2ywcg_ag']
[2023-05-03 18:35:13,219] {standard_task_runner.py:80} INFO - Job 854: Subtask extract_from_s3
[2023-05-03 18:35:13,638] {task_command.py:370} INFO - Running <TaskInstance: dag_etl.extract_from_s3 manual__2023-05-03T18:34:59.697678+00:00 [running]> on host 295d97741f96
[2023-05-03 18:35:14,372] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Victor
AIRFLOW_CTX_DAG_ID=dag_etl
AIRFLOW_CTX_TASK_ID=extract_from_s3
AIRFLOW_CTX_EXECUTION_DATE=2023-05-03T18:34:59.697678+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-03T18:34:59.697678+00:00
[2023-05-03 18:35:14,380] {s3.py:861} INFO - Downloading source S3 file from Bucket raw with path supermarket_sales.csv
[2023-05-03 18:35:14,467] {base.py:68} INFO - Using connection ID 'minio_conn' for task execution.
[2023-05-03 18:35:14,472] {base_aws.py:206} INFO - Credentials retrieved from login
[2023-05-03 18:35:15,275] {python.py:173} INFO - Done. Returned value was: /opt/***/data/***_tmp_w4816e5v
[2023-05-03 18:35:15,549] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag_etl, task_id=extract_from_s3, execution_date=20230503T183459, start_date=20230503T183512, end_date=20230503T183515
[2023-05-03 18:35:15,656] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-05-03 18:35:16,028] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
